[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = lambdas venv __pycache__ .git .pytest_cache
collect_ignore = ['lambdas', 'venv']
addopts = --ignore=lambdas --ignore=venv
